//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitHelp.Core.Validation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BitHelp.Core.Validation.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string DisplayValue {
            get {
                return ResourceManager.GetString("DisplayValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items are not the same.
        /// </summary>
        public static string EqualNumberItemsInvalid {
            get {
                return ResourceManager.GetString("EqualNumberItemsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value is {0}..
        /// </summary>
        public static string MinimumValidIs {
            get {
                return ResourceManager.GetString("MinimumValidIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not valid..
        /// </summary>
        public static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is valid..
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        public static string ValueCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ValueCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid boolean..
        /// </summary>
        public static string XBooleanInvalid {
            get {
                return ResourceManager.GetString("XBooleanInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must different {1}..
        /// </summary>
        public static string XCompareDifferentInvalid {
            get {
                return ResourceManager.GetString("XCompareDifferentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must equal {1}..
        /// </summary>
        public static string XCompareEqualInvalid {
            get {
                return ResourceManager.GetString("XCompareEqualInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        public static string XCompareLessInvalid {
            get {
                return ResourceManager.GetString("XCompareLessInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string XComparePlusInvalid {
            get {
                return ResourceManager.GetString("XComparePlusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has not been confirmed..
        /// </summary>
        public static string XConfirmedInvalid {
            get {
                return ResourceManager.GetString("XConfirmedInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid date time..
        /// </summary>
        public static string XDateTimeInvalid {
            get {
                return ResourceManager.GetString("XDateTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid decimal..
        /// </summary>
        public static string XDecimalInvalid {
            get {
                return ResourceManager.GetString("XDecimalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid double..
        /// </summary>
        public static string XDoubleInvalid {
            get {
                return ResourceManager.GetString("XDoubleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain exactly {1} characters..
        /// </summary>
        public static string XExactCharactersInvalid {
            get {
                return ResourceManager.GetString("XExactCharactersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain {1} element..
        /// </summary>
        public static string XExactItemsIsInvalid {
            get {
                return ResourceManager.GetString("XExactItemsIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid guid..
        /// </summary>
        public static string XGuidInvalid {
            get {
                return ResourceManager.GetString("XGuidInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid int..
        /// </summary>
        public static string XIntInvalid {
            get {
                return ResourceManager.GetString("XIntInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid long..
        /// </summary>
        public static string XLongInvalid {
            get {
                return ResourceManager.GetString("XLongInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain at most {1} characters..
        /// </summary>
        public static string XMaxCharactersInvalid {
            get {
                return ResourceManager.GetString("XMaxCharactersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain a maximum of {1} element..
        /// </summary>
        public static string XMaxItemsIsInvalid {
            get {
                return ResourceManager.GetString("XMaxItemsIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be greater than {1}..
        /// </summary>
        public static string XMaxValueInvalid {
            get {
                return ResourceManager.GetString("XMaxValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain at least {1} characters..
        /// </summary>
        public static string XMinCharactersInvalid {
            get {
                return ResourceManager.GetString("XMinCharactersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain at least {1} element..
        /// </summary>
        public static string XMinItemsIsInvalid {
            get {
                return ResourceManager.GetString("XMinItemsIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be less than {1}..
        /// </summary>
        public static string XMinValueInvalid {
            get {
                return ResourceManager.GetString("XMinValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is empty..
        /// </summary>
        public static string XNotEmptyInvalid {
            get {
                return ResourceManager.GetString("XNotEmptyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found..
        /// </summary>
        public static string XNotFound {
            get {
                return ResourceManager.GetString("XNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid..
        /// </summary>
        public static string XNotValid {
            get {
                return ResourceManager.GetString("XNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} value can be equal to {1}..
        /// </summary>
        public static string XNoValueCanEqual {
            get {
                return ResourceManager.GetString("XNoValueCanEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} value can be less to {1}..
        /// </summary>
        public static string XNoValueCanLess {
            get {
                return ResourceManager.GetString("XNoValueCanLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} value can be plus to {1}..
        /// </summary>
        public static string XNoValueCanPlus {
            get {
                return ResourceManager.GetString("XNoValueCanPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null or empty..
        /// </summary>
        public static string XNullOrEmpty {
            get {
                return ResourceManager.GetString("XNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have a caster between {1} and {2}..
        /// </summary>
        public static string XRangeCharactersInvalid {
            get {
                return ResourceManager.GetString("XRangeCharactersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain between {1} and {2} elements..
        /// </summary>
        public static string XRangeItemsInvalid {
            get {
                return ResourceManager.GetString("XRangeItemsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain a value between {1} and {2}..
        /// </summary>
        public static string XRangeValueInvalid {
            get {
                return ResourceManager.GetString("XRangeValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is requerid..
        /// </summary>
        public static string XRequired {
            get {
                return ResourceManager.GetString("XRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains repeated values..
        /// </summary>
        public static string XSingletonItemsInvalid {
            get {
                return ResourceManager.GetString("XSingletonItemsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid timespan..
        /// </summary>
        public static string XTimeSpanInvalid {
            get {
                return ResourceManager.GetString("XTimeSpanInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid url..
        /// </summary>
        public static string XUrlInvalid {
            get {
                return ResourceManager.GetString("XUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is valid..
        /// </summary>
        public static string XValid {
            get {
                return ResourceManager.GetString("XValid", resourceCulture);
            }
        }
    }
}
