//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitHelp.Core.Validation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BitHelp.Core.Validation.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string DisplayValue {
            get {
                return ResourceManager.GetString("DisplayValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value is {0}..
        /// </summary>
        internal static string MinimumValieIs {
            get {
                return ResourceManager.GetString("MinimumValieIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not valid..
        /// </summary>
        internal static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required..
        /// </summary>
        internal static string Requerid {
            get {
                return ResourceManager.GetString("Requerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is valid..
        /// </summary>
        internal static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid boolean..
        /// </summary>
        internal static string XBooleanInvalid {
            get {
                return ResourceManager.GetString("XBooleanInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has not been confirmed..
        /// </summary>
        internal static string XConfirmedInvalid {
            get {
                return ResourceManager.GetString("XConfirmedInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid date time..
        /// </summary>
        internal static string XDateTimeInvalid {
            get {
                return ResourceManager.GetString("XDateTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid decimal..
        /// </summary>
        internal static string XDecimalInvalid {
            get {
                return ResourceManager.GetString("XDecimalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid double..
        /// </summary>
        internal static string XDoubleInvalid {
            get {
                return ResourceManager.GetString("XDoubleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain exactly {1} characters..
        /// </summary>
        internal static string XExactCharactersInvalid {
            get {
                return ResourceManager.GetString("XExactCharactersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid guid..
        /// </summary>
        internal static string XGuidInvalid {
            get {
                return ResourceManager.GetString("XGuidInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid int..
        /// </summary>
        internal static string XIntInvalid {
            get {
                return ResourceManager.GetString("XIntInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid long..
        /// </summary>
        internal static string XLongInvalid {
            get {
                return ResourceManager.GetString("XLongInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain at most {1} characters..
        /// </summary>
        internal static string XMaxCharactersInvalid {
            get {
                return ResourceManager.GetString("XMaxCharactersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}..
        /// </summary>
        internal static string XMaxNumberInvalid {
            get {
                return ResourceManager.GetString("XMaxNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain at least {1} characters..
        /// </summary>
        internal static string XMinCharactersInvalid {
            get {
                return ResourceManager.GetString("XMinCharactersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        internal static string XMinNumberInvalid {
            get {
                return ResourceManager.GetString("XMinNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is empty..
        /// </summary>
        internal static string XNotEmptyInvalid {
            get {
                return ResourceManager.GetString("XNotEmptyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid..
        /// </summary>
        internal static string XNotValid {
            get {
                return ResourceManager.GetString("XNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have a caster between {1} and {2}..
        /// </summary>
        internal static string XRangeCharactersInvalid {
            get {
                return ResourceManager.GetString("XRangeCharactersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain a value between {1} and {2}..
        /// </summary>
        internal static string XRangeNumerInvalid {
            get {
                return ResourceManager.GetString("XRangeNumerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is requerid..
        /// </summary>
        internal static string XRequerid {
            get {
                return ResourceManager.GetString("XRequerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid timespan..
        /// </summary>
        internal static string XTimeSpanInvalid {
            get {
                return ResourceManager.GetString("XTimeSpanInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid url..
        /// </summary>
        internal static string XUrlInvalid {
            get {
                return ResourceManager.GetString("XUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is valid..
        /// </summary>
        internal static string XValid {
            get {
                return ResourceManager.GetString("XValid", resourceCulture);
            }
        }
    }
}
